import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).parent


def task_docs(clean=False):
    """Build the html docs using Sphinx."""
    # Delete Autogenerated files from previous run
    if clean:
        shutil.rmtree(str(HERE.joinpath("docs/modules/generated")), ignore_errors=True)
        shutil.rmtree(str(HERE.joinpath("docs/_build")), ignore_errors=True)
        shutil.rmtree(str(HERE.joinpath("docs/auto_examples")), ignore_errors=True)

    subprocess.run("sphinx-build -b html -j auto -d docs/_build docs docs/_build/html", shell=True, check=True)
