import re
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path

HERE = Path(__file__).parent


def _get_uv_bin() -> str:
    uv_bin = shutil.which("uv")
    if uv_bin:
        return uv_bin

    local_uv = Path.home() / ".local" / "bin" / "uv"
    if local_uv.exists():
        return str(local_uv)

    raise FileNotFoundError("Could not find the `uv` binary. Install uv or add it to PATH.")


def task_docs(clean=False):
    """Build the html docs using Sphinx."""
    # Delete Autogenerated files from previous run
    if clean:
        shutil.rmtree(str(HERE.joinpath("docs/modules/generated")), ignore_errors=True)
        shutil.rmtree(str(HERE.joinpath("docs/_build")), ignore_errors=True)
        shutil.rmtree(str(HERE.joinpath("docs/auto_examples")), ignore_errors=True)

    subprocess.run("sphinx-build -b html -j auto -d docs/_build docs docs/_build/html", shell=True, check=True)


def update_version_strings(file_path, new_version):
    # taken from:
    # https://stackoverflow.com/questions/57108712/replace-updated-version-strings-in-files-via-python
    version_regex = re.compile(r"(^_*?version_*?\s*=\s*\")(\d+\.\d+\.\d+-?\S*)\"", re.M)
    with file_path.open("r+") as f:
        content = f.read()
        f.seek(0)
        f.write(
            re.sub(
                version_regex,
                lambda match: f'{match.group(1)}{new_version}"',
                content,
            )
        )
        f.truncate()


def update_version(version: Sequence[str]):
    uv_bin = _get_uv_bin()
    if len(version) == 0:
        # no argument passed => return the current version
        subprocess.run([uv_bin, "version"], shell=False, check=True, capture_output=False)
    else:
        # update the version
        subprocess.run([uv_bin, "version", *version], shell=False, check=True)
        new_version = (
            subprocess.run([uv_bin, "version"], shell=False, check=True, capture_output=True)
            .stdout.decode()
            .strip()
            .split(" ", 1)[1:][0]
        )

        update_version_strings(HERE.joinpath("src/nilspodlib/__init__.py"), new_version)


def task_update_version():
    version_arr = sys.argv[1:] if len(sys.argv) > 1 else []
    update_version(version_arr)
